### ISSUE TITLE
Error during image generation

### ISSUE THREAD

**Issue by wwydmanski** [amotile/stable-diffusion-studio#12]
I'm trying to generate a basic image in the "Workshop" tab, as per the video instruction, but I'm always getting the same error from webgui server:

```
Error completing request
Arguments: (None, '0.005', 1, '', 'textual_inversion', 100000, 500, 500, '/home/ginterhauser/stable-diffusion-webui/textual_inversion_templates/style_filewords.txt', False, 'fantasy landscape', '', 15, 2, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/home/ginterhauser/stable-diffusion-webui/modules/ui.py", line 212, in f
    res = list(func(*args, **kwargs))
  File "/home/ginterhauser/stable-diffusion-webui/webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "/home/ginterhauser/stable-diffusion-webui/modules/hypernetworks/ui.py", line 33, in train_hypernetwork
    hypernetwork, filename = modules.hypernetworks.hypernetwork.train_hypernetwork(*args)
  File "/home/ginterhauser/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 200, in train_hypernetwork
    assert hypernetwork_name, 'hypernetwork not selected'
AssertionError: hypernetwork not selected
```

**Comment by wwydmanski** [comment]
OK, it was my fault - I was on an incompatible version of Automatic1111. `87db6f01cc6b118fe0c82c36c6686d72d060c417` works like a charm!
