### ISSUE TITLE
Insta-crash - different error

### ISSUE THREAD

**Issue by Inscape-Matt** [amotile/stable-diffusion-studio#18]
Hi there,

1. Running AUTOMATIC1111 at 7860, tested and generating images aok.
2. Kick off amotile-studio-win.exe, get the following:

Loading AUTOMATIC1111 config from: http://localhost:7860/config
C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:122
                        throw Error("No img2img function found");
                              ^

Error: No img2img function found
    at C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:122:31
    at step (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:33:23)
    at Object.next (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:14:53)
    at fulfilled (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I bet I'm doing something wrong, but posting just in case. Thanks!

**Comment by Inscape-Matt** [comment]
It was my mistake, fixed now -- thanks! Stoked to have this working!

**Comment by geoah** [comment]
@Inscape-Matt could you please elaborate on how you fixed this?
