### ISSUE TITLE
Generating images locally was successful for the web ui side, but not for your frontend.

### ISSUE THREAD

**Issue by 1229119561Weike** [amotile/stable-diffusion-studio#25]
Error: ENOENT: no such file or directory, stat 'D:\data/collected/'
    at Object.statSync (node:fs:1551:3)
    at Object.statSync (pkg/prelude/bootstrap.js:1479:32)
    at __node_internal_ (node:internal/fs/utils:799:8)
    at Object.rmSync (node:fs:1226:13)
    at C:\snapshot\stable-diffusion-backend\dist\http-server.js:82:32
    at Layer.handle [as handle_request] (C:\snapshot\stable-diffusion-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\snapshot\stable-diffusion-backend\node_modules\express\lib\router\route.js:144:13)
    at C:\snapshot\stable-diffusion-backend\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at invokeCallback (C:\snapshot\stable-diffusion-backend\node_modules\raw-body\index.js:231:16) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'D:\\data/collected/'

**Comment by amotile** [comment]
Does it work if you create that folder? It shouldn't be needed but worth trying.
The other thing you could try is running it as administrator. maybe there's some read access issues?

**Comment by 1229119561Weike** [comment]
This&nbsp;is&nbsp;really&nbsp;weird.&nbsp;I&nbsp;created&nbsp;folders&nbsp;and&nbsp;ran&nbsp;the&nbsp;program&nbsp;as&nbsp;administrator,&nbsp;but&nbsp;it&nbsp;still&nbsp;doesn't&nbsp;seem&nbsp;to&nbsp;work.







Loading AUTOMATIC1111 config from: http://localhost:7860/config
Socket listening on ws://localhost:4001/
Fractals, recursive loop, alien spaceship lands in Peach Blossom Land, Chinese style., black and white still, digital Art, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger.
Server listening on http://localhost:4000/
Error: No result!
&nbsp; &nbsp; at Object.<anonymous&gt; (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:160:35)
&nbsp; &nbsp; at step (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:33:23)
&nbsp; &nbsp; at Object.next (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:14:53)
&nbsp; &nbsp; at fulfilled (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:5:58)
&nbsp; &nbsp; at processTicksAndRejections (node:internal/process/task_queues:96:5)
Fractals, recursive loop, alien spaceship lands in Peach Blossom Land, Chinese style., black and white still, digital Art, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amotile/stable-diffusion-studio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amotile/stable-diffusion-studio] Generating images locally was successful for the web ui side, but not for your frontend. (Issue #25)





 
Does it work if you create that folder? It shouldn't be needed but worth trying.
 The other thing you could try is running it as administrator. maybe there's some read access issues?

**Comment by 1229119561Weike** [comment]
> Does it work if you create that folder? It shouldn't be needed but worth trying. The other thing you could try is running it as administrator. maybe there's some read access issues?

This is really weird. I created folders and ran the program as administrator, but it still doesn't seem to work.

Error: No result!
    at Object.<anonymous> (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:160:35)
    at step (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:33:23)
    at Object.next (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:14:53)
    at fulfilled (C:\snapshot\stable-diffusion-backend\dist\process\implementations\automatic1111.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by 1229119561Weike** [comment]
> Does it work if you create that folder? It shouldn't be needed but worth trying. The other thing you could try is running it as administrator. maybe there's some read access issues?

In my folder D:\data\output, the generated PNG file is 0kb and the json file is 1kb. The images generated by the front end display only a small image icon in the center.

**Comment by amotile** [comment]
How mysterious, I will try with the latest version of AUTOMATIC when I have time to see if they changed something.
