### ISSUE TITLE
windows exe version not interfacing correctly with latest Automatic1111?

### ISSUE THREAD

**Issue by Norgus** [amotile/stable-diffusion-studio#6]
I think there is some level of communication, because my automatic1111 SD command prompt does display this:
```Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Applying cross attention optimization (Doggettx).
Error completing request
Arguments: (None, '0.005', '', 'textual_inversion', 100000, 500, 500, 'C:\\Users\\norgu\\SD_Automatic111\\textual_inversion_templates\\style_filewords.txt', False, 'fantasy landscape', '', 15, 2, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "C:\Users\norgu\SD_Automatic111\modules\ui.py", line 187, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\norgu\SD_Automatic111\webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "C:\Users\norgu\SD_Automatic111\modules\hypernetworks\ui.py", line 33, in train_hypernetwork
    hypernetwork, filename = modules.hypernetworks.hypernetwork.train_hypernetwork(*args)
  File "C:\Users\norgu\SD_Automatic111\modules\hypernetworks\hypernetwork.py", line 184, in train_hypernetwork
    assert hypernetwork_name, 'hypernetwork not selected'
AssertionError: hypernetwork not selected
```

Since using the 'None' hypernetwork works fine in my usual webui, does this mean something is wrong with the API call?

**Comment by amotile** [comment]
Should be fixed in the new release, it was picking up the wrong function to use.

**Comment by Norgus** [comment]
can confirm that the new release fixed this! thanks
